pull_request_title: 'feat(lang): 🌐 Update translation files'
pull_request_labels:
  - 'translation'
commit_message: 'chore(lang): 🌐 Update %language% translation of %original_file_name% [no ci]'
append_commit_message: false

files:
  - source: /public/locales/en/*.json
    translation: /public/locales/%two_letters_code%/%original_file_name%
