name: Docker Publish

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Docker login
        run: |
          echo "${{ github.token }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      - name: 'Create env file'
        run: |
          touch build.env.local
          echo KEYCLOAK_URL="https://auth.buildtheearth.net/realms/website" >> build.env.local
          echo KEYCLOAK_ID="frontend" >> build.env.local
          echo KEYCLOAK_SECRET="${{ secrets.KEYCLOAK_SECRET }}" >> build.env.local
          echo NEXTAUTH_URL="https://buildtheearth.net" >> build.env.local
          echo NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" >> build.env.local
          echo NEXT_PUBLIC_API_URL="https://api.buildtheearth.net/api/v1" >> build.env.local
          echo NEXT_PUBLIC_MAPBOX_TOKEN="${{ secrets.MAPBOX_TOKEN }}" >> build.env.local
          echo PORT=3000 >> build.env.local

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/buildtheearth/website-frontend:$(git rev-parse --short HEAD) --tag ghcr.io/buildtheearth/website-frontend:latest
      - name: Docker push tag
        run: docker push ghcr.io/buildtheearth/website-frontend:$(git rev-parse --short HEAD)
      - name: Docker push latest
        run: docker push ghcr.io/buildtheearth/website-frontend:latest
