#!/usr/bin/env sh
command -v gpg-connect-agent >/dev/null 2>&1 && gpg-connect-agent reloadagent /bye >/dev/null 2>&1 || true
# Format staged files using Prettier and re-stage them
if git diff --cached --name-only --diff-filter=ACMR | grep -q .; then
  git diff --cached --name-only -z --diff-filter=ACMR | xargs -0 yarn exec prettier --write --ignore-unknown
  git diff --cached --name-only -z --diff-filter=ACMR | xargs -0 git add -f
fi
